Chat 222 be api 채팅 이미지 전송
Chat-Diary/BE pull request #43
Opened 2024-02-05 08:58 UTC by Kjiw0n

## 요약 (Summary)

- [x]  채팅 이미지 처리 기능 추가 및 관련 예외처리 로직 추가

## 변경 사항 (Changes)

- Request 중 chatType 타입 변경(`String` -> `ChatType(Enum)`)
- OpenAI API 이미지 처리 기능 추가
    - 이미지 처리 가능한 모델으로 변경 (gpt-3.5-turbo → gpt-4-vision-preview)
    - gpt 모델 변경에 따른 OpenAI 요청 폼 변경 반영
- 채팅 정보를 한번에 전달받기 위해선 String 형식으로 이미지를 전달받아야하므로 Base64 인코딩 방식 채택
    - `uploadBase64File` :해당 사항 반영하여 인코딩된 문자열을 받아서 파일 변환 후 S3에 업로드하는 메소드 추가
- 웹소켓 핸들러가 `chatType: “IMG”` 인 경우에 s3에 업로드 후 content 값을 이미지url로 변경하도록 하는 로직 추가
- `content` 타입 변경 (`varchar` → `text`)
    - Base64 인코딩 시 문자열의 길이가 상당히 길어지기 때문
- gpt processing 중 에러 발생 시 예외처리 로직 추가
    - `deleteUserMessage`: 저장된 사용자의 채팅 삭제

## 리뷰 요구사항

- [ ]  content 타입 변경 시에 문제가 없을 지 확인해주세요.
- [ ]  이미지 처리 로직에 문제가 없는 지 확인해주세요.
- [ ]  인코딩된 문자열 입력 시 s3에 정상적으로 업로드 되는 지 확인해주세요.
- [ ]  추가적으로 예외처리가 필요한 사항이 있다면 말씀 부탁드려요.

## 확인 방법 (선택)

chatType: “IMG” 로 설정 후 base64 인코딩된 문자열을 content에 입력하여 테스트를 진행하면 됩니다!

<img width="1582" alt="스크린샷 2024-02-05 17 53 18" src="https://github.com/Chat-Diary/BE/assets/128016888/f1076790-a20c-4ed3-91c9-c1fe68b7051a">

2024-02-07 08:12 UTC, Mouon approved these changes
포스트 맨을 통해 확인하였고, 업로드 또한 정상 처리됨을 확인하였습니다.

#### 포스트맨
<img width="1058" alt="스크린샷 2024-02-07 오후 5 11 12" src="https://github.com/Chat-Diary/BE/assets/137624597/b3ef0ff4-32a3-40ee-850b-6267d5d2ed22">

####  S3 정상 업로드
<img width="715" alt="스크린샷 2024-02-07 오후 5 11 46" src="https://github.com/Chat-Diary/BE/assets/137624597/6eee3e2e-a9ee-488e-b5ff-16b95d395e66">

2024-02-07 08:58 UTC, dainshon commented
작업량이 정말 많네요.>!! 
예외처리도 깔끔하고 메소드 분리도 가독성이 좋은것 같습니다:)
다만 제 로컬에서 실행했을때 
1. 이미지 인코딩의 길이에 따라 너무 길어 오류가 납니다. 받는 content 길이의 한계가 있는건가용?-?
짧은 길이의 content는 잘 동작합니다!
![image](https://github.com/Chat-Diary/BE/assets/81453127/000d8cd3-73b9-4786-b472-a9c3442c21ee)

2. 새로 주신 key로 했는데도 gptmessage 오류가 납니다ㅠㅠ 현준님 잘 되시는거 보니 제꺼만 이런것같기도합니다..!
![image](https://github.com/Chat-Diary/BE/assets/81453127/7fba2ffb-7419-4048-bb23-061ea274f177)

2024-02-07 13:19 UTC, Kjiw0n commented
> 작업량이 정말 많네요.>!! 예외처리도 깔끔하고 메소드 분리도 가독성이 좋은것 같습니다:) 다만 제 로컬에서 실행했을때
> 
> 1. 이미지 인코딩의 길이에 따라 너무 길어 오류가 납니다. 받는 content 길이의 한계가 있는건가용?-?
>    짧은 길이의 content는 잘 동작합니다!
>    ![image](https://private-user-images.githubusercontent.com/81453127/302909576-000d8cd3-73b9-4786-b472-a9c3442c21ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTIwODYsIm5iZiI6MTcwNzMxMTc4NiwicGF0aCI6Ii84MTQ1MzEyNy8zMDI5MDk1NzYtMDAwZDhjZDMtNzNiOS00Nzg2LWI0NzItYTljMzQ0MmMyMWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDEzMTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4M2I5YjkzZGM2MjE0NGM0ZDVmYTA0NWU1YTVhYzQ4YzBjNmUxMzJiNDhiYjg2YmNhMDBiNDExNjhjZWQxZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sS8jVFEMUO5gIV20h_w9sW_RJK80zClENTcm-JwzZW0)
> 2. 새로 주신 key로 했는데도 gptmessage 오류가 납니다ㅠㅠ 현준님 잘 되시는거 보니 제꺼만 이런것같기도합니다..!
>    ![image](https://private-user-images.githubusercontent.com/81453127/302909373-7fba2ffb-7419-4048-bb23-061ea274f177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTIwODYsIm5iZiI6MTcwNzMxMTc4NiwicGF0aCI6Ii84MTQ1MzEyNy8zMDI5MDkzNzMtN2ZiYTJmZmItNzQxOS00MDQ4LWJiMjMtMDYxZWEyNzRmMTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDEzMTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MTg0MTZkNjViNDMzMTY5ZTY2NjliYTBiNzQ4YTZkNTMwMmIxODM1YWUzY2MxNjVkNzgwN2FhYzQzMTJjZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lrnd4yaCPciCFUALGvsQPykNGVE0JNOgD4DnDfJF4zY)

1번 문제는 웹소켓 버퍼 크기 제한 문제로, 100KB까지 받을 수 있도록 수정하였습니다! 
2번 문제는 (GPT processing error) 혹시 로그 확인이 가능할까요??

2024-02-07 16:08 UTC, dainshon commented
> > 작업량이 정말 많네요.>!! 예외처리도 깔끔하고 메소드 분리도 가독성이 좋은것 같습니다:) 다만 제 로컬에서 실행했을때
> > 
> > 1. 이미지 인코딩의 길이에 따라 너무 길어 오류가 납니다. 받는 content 길이의 한계가 있는건가용?-?
> >    짧은 길이의 content는 잘 동작합니다!
> >    ![image](https://private-user-images.githubusercontent.com/81453127/302909576-000d8cd3-73b9-4786-b472-a9c3442c21ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTIwODYsIm5iZiI6MTcwNzMxMTc4NiwicGF0aCI6Ii84MTQ1MzEyNy8zMDI5MDk1NzYtMDAwZDhjZDMtNzNiOS00Nzg2LWI0NzItYTljMzQ0MmMyMWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDEzMTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4M2I5YjkzZGM2MjE0NGM0ZDVmYTA0NWU1YTVhYzQ4YzBjNmUxMzJiNDhiYjg2YmNhMDBiNDExNjhjZWQxZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sS8jVFEMUO5gIV20h_w9sW_RJK80zClENTcm-JwzZW0)
> > 2. 새로 주신 key로 했는데도 gptmessage 오류가 납니다ㅠㅠ 현준님 잘 되시는거 보니 제꺼만 이런것같기도합니다..!
> >    ![image](https://private-user-images.githubusercontent.com/81453127/302909373-7fba2ffb-7419-4048-bb23-061ea274f177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTIwODYsIm5iZiI6MTcwNzMxMTc4NiwicGF0aCI6Ii84MTQ1MzEyNy8zMDI5MDkzNzMtN2ZiYTJmZmItNzQxOS00MDQ4LWJiMjMtMDYxZWEyNzRmMTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDEzMTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MTg0MTZkNjViNDMzMTY5ZTY2NjliYTBiNzQ4YTZkNTMwMmIxODM1YWUzY2MxNjVkNzgwN2FhYzQzMTJjZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lrnd4yaCPciCFUALGvsQPykNGVE0JNOgD4DnDfJF4zY)
> 
> 1번 문제는 웹소켓 버퍼 크기 제한 문제로, 100KB까지 받을 수 있도록 수정하였습니다! 2번 문제는 (GPT processing error) 혹시 로그 확인이 가능할까요??

제 생각에는 인코딩된 이미지를 못알아먹는 것 같아요..!

2024-02-08T01:06:03.624+09:00 ERROR 73924 --- [onPool-worker-1] c.kuit.chatdiary.service.OpenAIService   : Error calling OpenAI API: 

org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{<EOL>  "error": {<EOL>    "message": "Invalid image.",<EOL>    "type": "invalid_request_error",<EOL>    "param": null,<EOL>    "code": null<EOL>  }<EOL>}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:932) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:881) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:781) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:529) ~[spring-web-6.1.2.jar:6.1.2]
	at com.kuit.chatdiary.service.OpenAIService.getCompletion(OpenAIService.java:57) ~[main/:na]
	at com.kuit.chatdiary.service.ChatService.processGptMessage(ChatService.java:51) ~[main/:na]
	at com.kuit.chatdiary.websocket.ChatWebSocketHandler.lambda$handleTextMessage$1(ChatWebSocketHandler.java:55) ~[main/:na]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]

2024-02-08T01:06:03.631+09:00 ERROR 73924 --- [onPool-worker-1] c.k.c.websocket.ChatWebSocketHandler     : GPT message processing failed

java.lang.RuntimeException: Error calling OpenAI API
	at com.kuit.chatdiary.service.OpenAIService.getCompletion(OpenAIService.java:61) ~[main/:na]
	at com.kuit.chatdiary.service.ChatService.processGptMessage(ChatService.java:51) ~[main/:na]
	at com.kuit.chatdiary.websocket.ChatWebSocketHandler.lambda$handleTextMessage$1(ChatWebSocketHandler.java:55) ~[main/:na]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{<EOL>  "error": {<EOL>    "message": "Invalid image.",<EOL>    "type": "invalid_request_error",<EOL>    "param": null,<EOL>    "code": null<EOL>  }<EOL>}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:932) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:881) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:781) ~[spring-web-6.1.2.jar:6.1.2]
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:529) ~[spring-web-6.1.2.jar:6.1.2]
	at com.kuit.chatdiary.service.OpenAIService.getCompletion(OpenAIService.java:57) ~[main/:na]
	... 9 common frames omitted

2024-02-08T01:06:03.640+09:00  INFO 73924 --- [onPool-worker-1] com.kuit.chatdiary.service.ChatService   : Deleting user chat with chatId: 41

2024-02-07 18:36 UTC, nonaninona reviewed
저도 같은 에러가 떠서 좀 알아보다가

getCompletion 메소드에서
messages에 previousMessages를 넣는 부분을 주석처리 했더니
<img width="647" alt="image" src="https://github.com/Chat-Diary/BE/assets/53222283/b75e4889-ee0d-4e20-aa40-0c45eb951ce9">
괜찮아지네요...
아마 이전 대화를 넣지 않아야 하는 걸 수도??

2024-02-07 18:44 UTC, nonaninona requested changes
.

2024-02-08 01:50 UTC, Mouon commented
> 저도 같은 에러가 떠서 좀 알아보다가
> 
> 
> 
> getCompletion 메소드에서
> 
> messages에 previousMessages를 넣는 부분을 주석처리 했더니
> 
> <img width="647" alt="image" src="https://github.com/Chat-Diary/BE/assets/53222283/b75e4889-ee0d-4e20-aa40-0c45eb951ce9">
> 
> 괜찮아지네요...
> 
> 아마 이전 대화를 넣지 않아야 하는 걸 수도??

저도 티스트할때 이전대화를 안넣으니까 되다라고요

2024-02-12 06:42 UTC, Kjiw0n commented
이전 대화 관련해서 수정 했습니다! 2가지 이미지 넣어서 비교 인식 잘 되는 지 확인하였습니다. 
db 타입을 변경해도 자동으로 업데이트가 안되는 둣 해서, content 타입 TEXT로 변경 후 테스트 진행해주시면 됩니다!

2024-02-12 12:24 UTC, nonaninona reviewed
1kb 크기의 이미지를 인코딩해서 업로드하는 건 성공했습니다!

잘 안되는 부분이
1. 테스트 데이터를 추가하고 진행하면 안됨
2. 30kb 크기의 이미지를 인코딩해서 진행할 때 안됨(에러 메시지는 20mb보다 커서 안된다고 뜸)

2가지 있는데요

원인 파악이 필요해보입니다

2024-02-13 17:24 UTC, Kjiw0n commented
> 1kb 크기의 이미지를 인코딩해서 업로드하는 건 성공했습니다!
> 
> 잘 안되는 부분이
> 
> 1. 테스트 데이터를 추가하고 진행하면 안됨
> 2. 30kb 크기의 이미지를 인코딩해서 진행할 때 안됨(에러 메시지는 20mb보다 커서 안된다고 뜸)
> 
> 2가지 있는데요
> 
> 원인 파악이 필요해보입니다

1. 테스트 데이터 추가 시 chatType이 IMG인 채팅의 content를 실제 imageUrl로 추가해야 정상 동작할 것 같습니다. 정상 동작하는 내용 확인하였습니다!
2. 인코딩 방식의 문제로 보입니다. 900KB 파일을 정상적으로 전송되는 것 확인하였으니, 이전 안내드린 방식으로 확인 부탁드려요!

2024-02-14 06:02 UTC, Mouon reviewed
#### S3 업로드
<img width="824" alt="스크린샷 2024-02-14 오후 2 53 53" src="https://github.com/Chat-Diary/BE/assets/137624597/d3c6aa45-5f1a-4005-b88f-424b692e609d">

#### 메세지 정상 반환
<img width="868" alt="스크린샷 2024-02-14 오후 2 54 36" src="https://github.com/Chat-Diary/BE/assets/137624597/a9374b14-f32a-430b-9e42-dca32d55b489">

연속적 메시지 전송으로도 확인했습니다. 

일부 이미지에 대해서는 인코딩 문자열이 너무 커서 테스트에 어려움이 있었습니다. 
쿼리로 임의의 채팅 삽입후 메세지 보내면 url에러가 뜨지만 실제 어플에서는 임의 쿼리는 없을것이기때문에 문제는 없을 것 같습니다.

2024-02-14 06:14 UTC, nonaninona commented
> #### S3 업로드
> <img alt="스크린샷 2024-02-14 오후 2 53 53" width="824" src="https://private-user-images.githubusercontent.com/137624597/304635614-d3c6aa45-5f1a-4005-b88f-424b692e609d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTE1MTEsIm5iZiI6MTcwNzg5MTIxMSwicGF0aCI6Ii8xMzc2MjQ1OTcvMzA0NjM1NjE0LWQzYzZhYTQ1LTVmMWEtNDAwNS1iODhmLTQyNGI2OTJlNjA5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwNjEzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODYzMzBmYzkwODg2NzhkZmZiY2NhYTRmY2VlMzE2MTQzYzQ3YTAzNWZjMDk0MTFlNjU0ODJiYTA1NjhmOGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dYXn58tgHzQFgCNp5Iv3HakjZ2qjfqbUKueIcl5PGd4">
> #### 메세지 정상 반환
> <img alt="스크린샷 2024-02-14 오후 2 54 36" width="868" src="https://private-user-images.githubusercontent.com/137624597/304635773-a9374b14-f32a-430b-9e42-dca32d55b489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTE1MTEsIm5iZiI6MTcwNzg5MTIxMSwicGF0aCI6Ii8xMzc2MjQ1OTcvMzA0NjM1NzczLWE5Mzc0YjE0LWYzMmEtNDMwYi05ZTQyLWRjYTMyZDU1YjQ4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwNjEzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjY1ZGRlZjFjYThlOThlNjQzNjBjODI5Nzg5M2RjZjNmODVkMzNlN2M0MTE5YWFiZDllNTdhM2Y3YWU4ZjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NvSBPydiQjqvyQfnH5k_qaps08L1Hkn_orLjfV1VkcI">
> 연속적 메시지 전송으로도 확인했습니다.
> 
> 일부 이미지에 대해서는 인코딩 문자열이 너무 커서 테스트에 어려움이 있었습니다. 쿼리로 임의의 채팅 삽입후 메세지 보내면 url에러가 뜨지만 실제 어플에서는 임의 쿼리는 없을것이기때문에 문제는 없을 것 같습니다.

혹시 임의의 쿼리가 어떤 형식인가요??
제가 올려놨던 Ver4 쿼리가 내용이 잘 못 채워져서 오류가 날 수도 있습니다

2024-02-14 07:08 UTC, Mouon commented
> > #### S3 업로드
> > <img alt="스크린샷 2024-02-14 오후 2 53 53" width="824" src="https://private-user-images.githubusercontent.com/137624597/304635614-d3c6aa45-5f1a-4005-b88f-424b692e609d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTE1MTEsIm5iZiI6MTcwNzg5MTIxMSwicGF0aCI6Ii8xMzc2MjQ1OTcvMzA0NjM1NjE0LWQzYzZhYTQ1LTVmMWEtNDAwNS1iODhmLTQyNGI2OTJlNjA5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwNjEzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODYzMzBmYzkwODg2NzhkZmZiY2NhYTRmY2VlMzE2MTQzYzQ3YTAzNWZjMDk0MTFlNjU0ODJiYTA1NjhmOGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dYXn58tgHzQFgCNp5Iv3HakjZ2qjfqbUKueIcl5PGd4">
> > #### 메세지 정상 반환
> > <img alt="스크린샷 2024-02-14 오후 2 54 36" width="868" src="https://private-user-images.githubusercontent.com/137624597/304635773-a9374b14-f32a-430b-9e42-dca32d55b489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTE1MTEsIm5iZiI6MTcwNzg5MTIxMSwicGF0aCI6Ii8xMzc2MjQ1OTcvMzA0NjM1NzczLWE5Mzc0YjE0LWYzMmEtNDMwYi05ZTQyLWRjYTMyZDU1YjQ4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwNjEzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjY1ZGRlZjFjYThlOThlNjQzNjBjODI5Nzg5M2RjZjNmODVkMzNlN2M0MTE5YWFiZDllNTdhM2Y3YWU4ZjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NvSBPydiQjqvyQfnH5k_qaps08L1Hkn_orLjfV1VkcI">
> > 연속적 메시지 전송으로도 확인했습니다.
> > 일부 이미지에 대해서는 인코딩 문자열이 너무 커서 테스트에 어려움이 있었습니다. 쿼리로 임의의 채팅 삽입후 메세지 보내면 url에러가 뜨지만 실제 어플에서는 임의 쿼리는 없을것이기때문에 문제는 없을 것 같습니다.
> 
> 혹시 임의의 쿼리가 어떤 형식인가요?? 제가 올려놨던 Ver4 쿼리가 내용이 잘 못 채워져서 오류가 날 수도 있습니다

버전 5로하니 정상적으로 작동하는거 확인 되었습니다.

2024-02-14 10:45 UTC, Mouon approved these changes
지라에 있는 새로운 쿼리문을통해 임의의 쿼리 추가하고 채팅해도 이상 없는 것 확인했습니다.

2024-02-14 11:59 UTC, dainshon commented
이전과같은 에러도없고 조금 큰 이미지 전송도 문제없고 s3저장도 잘 됩니다! 고생했어요오:>

에러는 아니고 gpt가 "I'm sorry for any confusion, but it seems there has been a misunderstanding. If you have any questions or need assistance, feel free to ask!" 이런 답변을 주는데 얘는 지피티가 문제겠죠..?!!

2024-02-14 12:10 UTC, Kjiw0n commented
에러 로그나 다른 문제가 보이지 않는다면, 찾아 본 결과 해당 문제는 말씀하신 대로 GPT의 문제로 생각됩니다!

2024-02-14 12:13 UTC, nonaninona commented
> 이전과같은 에러도없고 조금 큰 이미지 전송도 문제없고 s3저장도 잘 됩니다! 고생했어요오:>
> 
> 에러는 아니고 gpt가 "I'm sorry for any confusion, but it seems there has been a misunderstanding. If you have any questions or need assistance, feel free to ask!" 이런 답변을 주는데 얘는 지피티가 문제겠죠..?!!

어쨋든 말은 하니까요 ㅋㅋ 그냥 이해를 못한듯 무슨 대답을 원하는지

2024-02-14 12:13 UTC, nonaninona approved these changes

2024-02-14 12:13 UTC, merged