Feat : CHAT-257-BE-공지사항-리스트&상세
Chat-Diary/BE pull request #47
Opened 2024-02-11 06:52 UTC by Mouon

구체적으로 논의되고 필수는 아니라 우선 구성해 보았습니다.

## 요약 (Summary)
- [x] 공지사항 리스트 api작성
- [x] 공지사항 상세 api작성

## 변경 사항 (Changes)
- 공지사항 리스트 조회 API를 구현하였습니다. 해당 API는 모든 공지사항을 리스트 형태로 반환합니다.
- 공지사항 상세 조회 API를 구현하였습니다. 해당 API는 공지사항의 ID를 기반으로 해당 공지사항의 상세 정보를 반환합니다.
## 리뷰 요구사항
- [ ]  공지사항 데이터 접근 로직이 효율적으로 작성되었는지 확인해 주세요.
- [ ] 적절하게 응답이 오는지 확인해주세요

## 확인 방법 

### 요청 주소 예시

#### 공지사항 리스트
```
http://localhost:8080/notice/list
```

#### 공지사항 상세
```
http://localhost:8080/notice/detail?noticeId=1
```

### 쿼리 예시

```
INSERT INTO notice (title, content, notice_date,create_at, update_at) VALUES
('챗 다이어리 가입이벤트', 'PM이 쏜다! 신규 가입자중 10명을 추첩해서 맥북 m3를쏩니다','2024-02-01',NOW(), NOW()),
('챗 다이어리 치치를 잡아라', '치치를 잡아라!', '2024-02-02',NOW(), NOW()),
('챗 다이어리 신규 캐릭 공지', '치치 다다 루루에 이어서 곧 새로운 캐릭터가 공개됩니다. 이 캐릭터는 학습 상담도 해준데요!','2024-02-15', NOW(), NOW());

```

### 포스트맨

#### 리스트
<img width="868" alt="스크린샷 2024-02-11 오후 3 49 53" src="https://github.com/Chat-Diary/BE/assets/137624597/5dd49479-57de-415f-9b53-0c135d50571a">

#### 상세
<img width="868" alt="스크린샷 2024-02-11 오후 3 49 26" src="https://github.com/Chat-Diary/BE/assets/137624597/bb020e10-31bc-4ff7-ae8b-a83ee0a5dbd3">

2024-02-12 07:39 UTC, Kjiw0n approved these changes
테스트 정상동작 하는 것 확인하였습니다!

2024-02-12 07:39 UTC, Kjiw0n commented on src/main/java/com/kuit/chatdiary/controller/notice/NoticeController.java
> +    }
로딩이 길어질 듯 하여, 해당 경로에서는 공지사항 content는 제외하는 방법도 좋아보입니다!

2024-02-12 10:09 UTC, Mouon commented on src/main/java/com/kuit/chatdiary/controller/notice/NoticeController.java
> +    }
리스트에서 내용미리보기 생각했던것인데 
없는것이라면 제외하겠습니다

2024-02-12 10:10 UTC, nonaninona commented on src/main/java/com/kuit/chatdiary/controller/notice/NoticeController.java
> +    }
<img width="289" alt="image" src="https://github.com/Chat-Diary/BE/assets/53222283/7fb185bc-2112-4bda-93bf-be18d8a0acb2">

2024-02-12 10:11 UTC, Mouon commented on src/main/java/com/kuit/chatdiary/controller/notice/NoticeController.java
> +    }
제외하겠습니다~

2024-02-12 10:21 UTC, Mouon commented on src/main/java/com/kuit/chatdiary/controller/notice/NoticeController.java
> +    }
> <img alt="image" width="289" src="https://private-user-images.githubusercontent.com/53222283/304017885-7fb185bc-2112-4bda-93bf-be18d8a0acb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzM0MTIsIm5iZiI6MTcwNzczMzExMiwicGF0aCI6Ii81MzIyMjI4My8zMDQwMTc4ODUtN2ZiMTg1YmMtMjExMi00YmRhLTkzYmYtYmUxOGQ4YTBhY2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwMTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYjIxMmE1NzI5Y2VkMTUzYmU2NTU2NTMyOWQxMDY4ZTQwNWQwYjY0OGFkYjA5YTk5ZTNmODBiYWRhZmFmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WLcb2XK464tqL4LdpnzAq8kBU2FneY4VT3ZVEsRj8b8">



<img width="868" alt="스크린샷 2024-02-12 오후 7 20 57" src="https://github.com/Chat-Diary/BE/assets/137624597/8791df6e-c77c-49ab-b801-3d698287b95f">

2024-02-12 11:32 UTC, dainshon requested changes
컨트롤러에서 List<NoticeResponseDTO> -> List<Notice**List**ResponseDTO> 만 바꿔주면 결과 잘 나옵니다!

2024-02-12 11:32 UTC, dainshon commented on src/main/java/com/kuit/chatdiary/controller/notice/NoticeController.java
> +    public ResponseEntity<List<NoticeResponseDTO>> getNoticeList(){
반환 타입이 NoticeListResopnseDTO로 바뀌어 컨트롤러에서도 바꿔줘야할것같아요!

2024-02-12 12:13 UTC, Mouon commented on src/main/java/com/kuit/chatdiary/controller/notice/NoticeController.java
> +    public ResponseEntity<List<NoticeResponseDTO>> getNoticeList(){
커밋에서 누락되었었습니다. 지금 다시 추가하였습니다. 확인 부탁드립니다.

2024-02-14 09:14 UTC, dainshon commented on src/main/java/com/kuit/chatdiary/controller/notice/NoticeController.java
> +    public ResponseEntity<List<NoticeResponseDTO>> getNoticeList(){
확인했습니다. 정상적으로 동작합니다!:)

2024-02-14 09:14 UTC, dainshon approved these changes

2024-02-14 09:37 UTC, merged